package com.green.machine.disposer.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 *
 * This class is generated by Vaadin Designer and will be overwritten.
 *
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainPage extends HorizontalLayout {
    protected CssLayout menu_part;
    protected CssLayout layout;
    protected HorizontalLayout menuTitle;
    protected Button menuToggle;
    protected CssLayout menuItems;
    protected Button visualizationLabel;
    protected Button mapLabel;
    protected Button assetLabel;
    protected Button reportsLabel;
    protected Button integrationLabel;
    protected MenuBar settings;
    protected Button logoutButton;
    protected HorizontalLayout overlayMenu;
    protected CssLayout arrow;
    protected CssLayout itemContainer;
    protected Button dashboard;
    protected Button mapLayers;
    protected Button livemapButton;
    protected Button geoFences;
    protected Button geoFenceGroups;
    protected Button locations;
    protected Button locationGroups;
    protected Button tripPlan;
    protected Button tripPlayer;
    protected Button vehicles;
    protected Button vessels;
    protected Button groups;
    protected Button assetMaintenance;
    protected Button alerts;
    protected Button mileage;
    protected Button fuel;
    protected Button maintenance;
    protected Button endpoint;
    protected Button devices;
    protected Button sensors;
    protected CssLayout content;

    public MainPage() {
        Design.read(this);
    }
}
